### ISSUE TITLE
releaser.toml syntax

### ISSUE THREAD

**Issue by ManiProjs** [vedantmgoyal9/rustreleaser#3]
Hi @vedantmgoyal9, I want to have releaser.toml syntax, because I don't know how to use `rustreleaser` to publish (I just wanna test it and contribute).

**Comment by ManiProjs** [comment]
@vedantmgoyal9 Can you see my issue?

**Comment by vedantmgoyal9** [comment]
hi @ManiProjs, apologies for the late reply. this project is now deprecated as rust support is now added to goreleaser.

**Comment by ManiProjs** [comment]
Wow, thanks!

**Comment by ManiProjs** [comment]
You can archive this organization by going to Settings of this organization (@rustreleaser-org), scroll down and find Danger Zone, click on Archive this organization and follow the steps to archive it
